### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Tellenwong** [learn-co-curriculum/dsc-intro-to-css#1]
Under the section for 'List the Components of CSS', the instruction refers to the 'welcome-message' class name, but the HTML refers to 'helpful-hint' as the class name.

/*
select all elements that have the **'welcome-message'** classname (e.g. <p class='helpful-hint'>
and <p class='helpful-hint'>)
*/
.helpful-hint

**Comment by jessepisel** [comment]
fixed with https://github.com/learn-co-curriculum/dsc-intro-to-css/commit/125b5d392afac246606b6141a8f58b8982ca1360
